# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DevSTR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DevSTR
pod 'ObjectMapper', '~> 3.2'
pod 'Alamofire', '~> 4.7'
pod 'Toast-Swift', '~> 3.0.1'
end
